#!/bin/bash

# Copyright <2022> Amazon.com, Inc. or its affiliates. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

PKG_INSTALL_DIR=/Applications/timestream-odbc
FINAL_INSTALL_DIR=/Library/ODBC/timestream-odbc

# Remove install directory if it already exists
if [ -d "${FINAL_INSTALL_DIR}" ]; then
    # Fail if FINAL_INSTALL_DIR is not set for whatever reason
    if [ -z ${FINAL_INSTALL_DIR} ]; then exit 1; fi
    rm -rf ${FINAL_INSTALL_DIR}
fi

# Move PKG installed folders to intended install directory
mkdir -p ${FINAL_INSTALL_DIR}
mv ${PKG_INSTALL_DIR}/lib ${FINAL_INSTALL_DIR}/lib
mv ${PKG_INSTALL_DIR}/doc ${FINAL_INSTALL_DIR}/doc

ODBCINST_INI=/Library/ODBC/odbcinst.ini
odbc_drivers=`grep "\[ODBC Drivers\]" /Library/ODBC/odbcinst.ini`
INSTALLED=`grep "Amazon Timestream ODBC Driver" /Library/ODBC/odbcinst.ini`
if [ -z "${INSTALLED}" ]
then
    if [ -z "${odbc_drivers}" ]
    then 
        echo -e "[ODBC Drivers]" >> $ODBCINST_INI
        echo "Amazon Timestream ODBC Driver = Installed" >> $ODBCINST_INI
    else
        sed -i -e "s/\[ODBC Drivers\]/\[ODBC Drivers\]\nAmazon Timestream ODBC Driver = Installed/g" $ODBCINST_INI
    fi
    echo -e "\n[Amazon Timestream ODBC Driver]" >> $ODBCINST_INI
    echo "Driver = ${FINAL_INSTALL_DIR}/lib/libtimestream-odbc.dylib" >> $ODBCINST_INI
    echo "Setup = ${FINAL_INSTALL_DIR}/lib/libtimestream-odbc.dylib" >> $ODBCINST_INI
else 
    echo "Amazon Timestream ODBC Driver might have been installed, please check $ODBCINST_INI!"
fi
